spring:
  application:
    name: flash
  datasource:
    url: jdbc:postgresql://localhost:5432/flash
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: false
  data:
    redis:
      host: localhost
      port: 6379
      username: default
      password: password
  kafka:
    bootstrap-servers: localhost:9092

management:
  endpoints:
    web:
      exposure:
        include: '*'

security:
  jwt:
    key-for-access: cXdlcnR5cXdlcnR5cXdydHl5dHJ0ZXRldHJycnJycnRydHJydHJlcnRldGV0cnJ0ZXJ0dHJ0cnRydHJ0cnRydHF3ZXJ0eQ==
    key-for-refresh: d2VxZGxzZnNnaGZoZHNkaGRmaGRmZ3J0cnRydHJ0cnR0dHR0dHR0dHR0dHR0dHR0dHR0dHR0cnRldHJ0
    access-token-life-time: 1000000
    refresh-token-life-time: 1000000

ticket:
  timeToLiveInSeconds: 300

kafka:
  producer:
    notification: notification.send

notification:
  templates:
    new-message-text: "Пользователь '%s' отправил вам сообщение: '%s'"
    new-message-title: "Сообщение от '%s'"
