spring:
  application:
    name: flash
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:flash}
    username: ${POSTGRES_USER:user}
    password: ${POSTGRES_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      username: ${REDIS_USERNAME:default}
      password: ${REDIS_PASSWORD:password}
  kafka:
    bootstrap-servers: ${KAFKA_SERVERS:localhost:9092}

management:
  endpoints:
    web:
      exposure:
        include: '*'

security:
  jwt:
    key-for-access: qwertyqwertyqwrtyytrtetetrrrrrrtrtrrtrertetetrrterttrtrtrtrtrtrtqwerty
    key-for-refresh: weqdlsfsghfhdsdhdfhdfgrtrtrtrtrtttttttttttttttttttttttrtetrt
    access-token-life-time: 10000
    refresh-token-life-time: 50000

ticket:
  timeToLiveInSeconds: 300

kafka:
  producer:
    notification: notification.send

notification:
  templates:
    new-message-text: "Пользователь '%s' отправил вам сообщение: '%s'"
    new-message-title: "Сообщение от '%s'"
