spring:
  application:
    name: flash
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:flash}
    username: ${POSTGRES_USER:user}
    password: ${POSTGRES_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false


security:
  jwt:
    key-for-access: qwertyqwertyqwrtyytrtetetrrrrrrtrtrrtrertetetrrterttrtrtrtrtrtrtqwerty
    key-for-refresh: weqdlsfsghfhdsdhdfhdfgrtrtrtrtrtttttttttttttttttttttttrtetrt
    access-token-life-time: 10000
    refresh-token-life-time: 50000
