name: flash

volumes:
  postgres:
  redis:

networks:
  common:

services:
  postgres:
    image: postgres:17
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-flash}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_USER=${POSTGRES_USER:-user}
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - common

  redis:
    image: redis:8.0.1
    restart: unless-stopped
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-password} # логин - default
    ports:
      - '6379:6379'
    networks:
      - common


  kafka:
    image: apache/kafka:3.9.1
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT_HOST://localhost:9092,PLAINTEXT://kafka:19092'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_LISTENERS: 'CONTROLLER://:29093,PLAINTEXT_HOST://:9092,PLAINTEXT://:19092'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      CLUSTER_ID: '4L6g3nShT-eMCtK--X86sw'
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - '9092:9092'
    networks:
      - common

  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    environment:
      KAFKA_CLUSTERS_0_NAME: 'kafka-skb-0'
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: 'kafka:19092'
    #      AUTH_TYPE: 'LOGIN_FORM'
    #      SPRING_SECURITY_USER_NAME: 'admin'
    #      SPRING_SECURITY_USER_PASSWORD: 'pass'
    #      SERVER_SERVLET_CONTEXT_PATH: '/'
    ports:
      - '8081:8080'
    depends_on:
      - kafka
    networks:
      - common

  notification:
    build:
      context: ./flash-notification
      dockerfile: Dockerfile
    environment:
      - MAIL_USERNAME=${MAIL_USERNAME:-SET_LOGIN}
      - MAIL_PASSWORD=${MAIL_PASSWORD:-SET_PASS}
      - KAFKA_SERVERS=kafka:19092
    #    ports:
    #      - '8082:8082'
    depends_on:
      - kafka
    networks:
      - common

  app:
    build:
      context: ./flash
      dockerfile: Dockerfile
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST:-postgres}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_DB=${POSTGRES_DB:-flash}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_USER=${POSTGRES_USER:-user}
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_USERNAME=${REDIS_USERNAME:-default}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-password}
      - KAFKA_SERVERS=${KAFKA_SERVERS:-kafka:19092}
    ports:
      - '8080:8080'
    depends_on:
      - kafka
      - postgres
      - redis
    networks:
      - common
